stages:
  - build-unit-test
  - install
  - integration-test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=/cache/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

test:
  stage: build-unit-test
  image: $CI_REGISTRY/research/coe-maven-centos:latest
  script:
    - mvn $MAVEN_CLI_OPTS clean verify
  tags:
    - docker

maven-install:
  stage: install
  image: $CI_REGISTRY/research/coe-maven-centos:latest
  script:
    - mvn $MAVEN_CLI_OPTS install -DskipTests
  tags:
    - docker

maven-deploy-base:
  stage: deploy
  image: $CI_REGISTRY/research/coe-maven-centos:latest
  script:
    - cd base
    - mvn $MAVEN_CLI_OPTS deploy -DskipTests -Pcoe
    - cd -
  tags:
    - docker
  only:
    - master
    - tags
