stages:
  - build-unit-test
  - install
  - integration-test
  - deploy
  - docker

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=/cache/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

test:
  stage: build-unit-test
  image: $CI_REGISTRY/research/coe-maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS clean verify
  tags:
    - docker

maven-install:
  stage: install
  image: $CI_REGISTRY/research/coe-maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS install -DskipTests
  tags:
    - docker

maven-deploy:
  stage: deploy
  image: $CI_REGISTRY/research/coe-maven:latest
  script:
    - cd base
    - mvn $MAVEN_CLI_OPTS clean deploy -B -Pcoe
    - cd -
  tags:
    - docker
  only:
    - master

docker-deploy-eng:
  stage: docker
  script:
    - cd eng
    - docker build -t $CI_REGISTRY/research/concrete-stanford-eng:latest .
    - docker push $CI_REGISTRY/research/concrete-stanford-eng:latest
  tags:
    - shell
  only:
    - master
